name: publish
run-name: publish /${{ github.ref_name }} on cloudflare

on:
  workflow_run:
    workflows: ["quality"]
    branches: ["master"]
    types:
      - completed

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN_MASTER }}
          accountId: 0b8a40ece224666bc2c0a0c7e6d4a59e
          projectName: symap
          directory: dist/symap/browser
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          wranglerVersion: '3'
