name: Quality

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup dependency caching
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - run: npm ci

  test:
    needs: install-dependencies
    runs-on: ${{ needs.get-runner.outputs.RUNNER }}
    steps:
      - name: Run tests
        run: npm run tests

  lint:
    needs: install-dependencies
    runs-on: ${{ needs.get-runner.outputs.RUNNER }}
    steps:
      - name: Run lint
        run: npm run lint
